apiVersion: v1
kind: Service
metadata:
  name: vc-server
  namespace: petdid-network
  labels:
    app: vc-server
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  selector:
    app: vc-server
