apiVersion: apps/v1
kind: Deployment
metadata:
  name: vc-server
  namespace: petdid-network
  labels:
    app: vc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vc-server
  template:
    metadata:
      labels:
        app: vc-server
    spec:
      containers:
      - name: vc-server
        image: vc-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
          name: grpc
        envFrom:
        - configMapRef:
            name: vc-server-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
