apiVersion: v1
kind: ConfigMap
metadata:
  name: vc-server-config
  namespace: petdid-network
data:
  ENV: "production"
  DB_TYPE: "postgres"
  DB_HOST: "vc-postgres"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  DB_DATABASE: "vc"
