apiVersion: v1
kind: Service
metadata:
  name: vc-postgres
  namespace: petdid-network
  labels:
    app: vc-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: vc-postgres
