apiVersion: apps/v1
kind: Deployment
metadata:
  name: vc-postgres
  namespace: petdid-network
  labels:
    app: vc-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vc-postgres
  template:
    metadata:
      labels:
        app: vc-postgres
    spec:
      containers:
      - name: vc-postgres
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "vcserver"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-storage
        emptyDir: {}
